export interface PaletteTemplate {
  id: string;
  name: string;
  description: string;
  primaryColor: string;
  secondaryColor: string;
  backgroundColor: string;
  accentColor: string;
  textColor: string;
  cardBackground: string;
}

export const PALETTE_TEMPLATES: PaletteTemplate[] = [
  {
    id: "fresh_harvest_promax",
    name: "Fresh Harvest Pro Max",
    description: "Vibrancia Orgánica y Contraste Superior",
    primaryColor: "#25B16B",
    secondaryColor: "#06162B",
    backgroundColor: "#F9F5EF",
    accentColor: "#FFA729",
    textColor: "#06162B",
    cardBackground: "#FFFFFF",
  },
  {
    id: "golden_crust_promax",
    name: "Golden Crust Pro Max",
    description: "Premium, Cálido y Artesanal",
    primaryColor: "#D2A547",
    secondaryColor: "#1F1B16",
    backgroundColor: "#FAF9F7",
    accentColor: "#E86417",
    textColor: "#1F1B16",
    cardBackground: "#FFFFFF",
  },
  {
    id: "cyber_chef_promax",
    name: "Cyber Chef Pro Max",
    description: "Moderno, Nocturno y Tecnológico",
    primaryColor: "#B16BE0",
    secondaryColor: "#0D0A14",
    backgroundColor: "#0D0A14",
    accentColor: "#29D6E8",
    textColor: "#F0F6FC",
    cardBackground: "#1A1626",
  },
  {
    id: "mediterranean_olive_promax",
    name: "Mediterranean Pro Max",
    description: "Tradición y Frescura Saludable",
    primaryColor: "#6A8A3D",
    secondaryColor: "#152929",
    backgroundColor: "#FEFAE0",
    accentColor: "#F25129",
    textColor: "#152929",
    cardBackground: "#FFFFFF",
  },
  {
    id: "gourmet",
    name: "Alta Cocina & Gourmet",
    description: "Lujo y Elegancia",
    primaryColor: "#C9A063",
    secondaryColor: "#1F2937",
    backgroundColor: "#0D1117",
    accentColor: "#FFFFFF",
    textColor: "#F0F6FC",
    cardBackground: "#161B22",
  },
  {
    id: "organic",
    name: "Orgánico & Saludable",
    description: "Frescura Natural",
    primaryColor: "#6B8F71",
    secondaryColor: "#B9C4B1",
    backgroundColor: "#F8F9F5",
    accentColor: "#2C3E2D",
    textColor: "#2C3E2D",
    cardBackground: "#FFFFFF",
  },
  {
    id: "fusion",
    name: "Fusión Moderna",
    description: "Vanguardia y Energía",
    primaryColor: "#FF3E00",
    secondaryColor: "#1A1A1A",
    backgroundColor: "#050505",
    accentColor: "#00F2FF",
    textColor: "#FFFFFF",
    cardBackground: "#0F0F0F",
  },
  {
    id: "seafood",
    name: "Pescados & Mariscos",
    description: "Estilo Mediterráneo",
    primaryColor: "#0077B6",
    secondaryColor: "#90E0EF",
    backgroundColor: "#F0F7FF",
    accentColor: "#CAF0F8",
    textColor: "#03045E",
    cardBackground: "#FFFFFF",
  },
  {
    id: "steakhouse",
    name: "Parrilla & Steakhouse",
    description: "Tradición y Fuego",
    primaryColor: "#8B2635",
    secondaryColor: "#3E2723",
    backgroundColor: "#1A0F0A",
    accentColor: "#D4A373",
    textColor: "#FAEDCD",
    cardBackground: "#2B1D19",
  },
  {
    id: "zen",
    name: "Zen & Japonés",
    description: "Minimalismo y Calma",
    primaryColor: "#111111",
    secondaryColor: "#E5E5E5",
    backgroundColor: "#FFFFFF",
    accentColor: "#999999",
    textColor: "#111111",
    cardBackground: "#F5F5F5",
  },
  {
    id: "pastry",
    name: "Pastelería & Dulces",
    description: "Suavidad y Color",
    primaryColor: "#F7AEF8",
    secondaryColor: "#B3DEE2",
    backgroundColor: "#FFFAFB",
    accentColor: "#FBE7C6",
    textColor: "#4A4A4A",
    cardBackground: "#FFFFFF",
  },
  {
    id: "brewery",
    name: "Cervecería & Industrial",
    description: "Robusto y Urbano",
    primaryColor: "#D97706",
    secondaryColor: "#404040",
    backgroundColor: "#121212",
    accentColor: "#FBBF24",
    textColor: "#E5E5E5",
    cardBackground: "#1A1A1A",
  },
  {
    id: "burger",
    name: "Burgers & Fast Food",
    description: "Dinámico y Directo",
    primaryColor: "#E11D48",
    secondaryColor: "#FBBF24",
    backgroundColor: "#FFFFFF",
    accentColor: "#111827",
    textColor: "#111827",
    cardBackground: "#F9FAFB",
  },
  {
    id: "tropical",
    name: "Bar Tropical & Cocktails",
    description: "Exótico y Vibrante",
    primaryColor: "#10B981",
    secondaryColor: "#F97316",
    backgroundColor: "#064E3B",
    accentColor: "#EC4899",
    textColor: "#ECFDF5",
    cardBackground: "#064E3B",
  },
  {
    id: "trattoria",
    name: "Trattoria Italiana",
    description: "Raíces y Sabor Tradicional",
    primaryColor: "#BC6C25",
    secondaryColor: "#606C38",
    backgroundColor: "#FEFAE0",
    accentColor: "#DDA15E",
    textColor: "#283618",
    cardBackground: "#FFFFFF",
  },
  {
    id: "coffee",
    name: "Cafetería & Tostaduría",
    description: "Aroma y Profundidad",
    primaryColor: "#D4A373",
    secondaryColor: "#A98467",
    backgroundColor: "#2C1B10",
    accentColor: "#FEFAE0",
    textColor: "#FAEDCD",
    cardBackground: "#3B2B1D",
  },
];
