export interface PaletteTemplate {
  id: string;
  name: string;
  description: string;
  primaryColor: string;
  secondaryColor: string;
  backgroundColor: string;
  accentColor: string;
  textColor: string;
  cardBackground: string;
  fontTitle: string;
  fontBody: string;
  fontAccent: string;
}

export const PALETTE_TEMPLATES: PaletteTemplate[] = [
  {
    id: "fresh_harvest",
    name: "Huerta Orgánica",
    description: "Frescura natural y contraste superior para conceptos saludables.",
    primaryColor: "#25B16B",
    secondaryColor: "#06162B",
    backgroundColor: "#F9F5EF",
    accentColor: "#FFA729",
    textColor: "#06162B",
    cardBackground: "#FFFFFF",
    fontTitle: "Outfit",
    fontBody: "Inter",
    fontAccent: "Outfit",
  },
  {
    id: "golden_crust",
    name: "Artesano & Trigo",
    description: "Calidez de panadería tradicional y repostería de autor.",
    primaryColor: "#D2A547",
    secondaryColor: "#1F1B16",
    backgroundColor: "#FAF9F7",
    accentColor: "#E86417",
    textColor: "#1F1B16",
    cardBackground: "#FFFFFF",
    fontTitle: "Cinzel",
    fontBody: "Montserrat",
    fontAccent: "Cinzel",
  },
  {
    id: "cyber_chef",
    name: "Neon Night Fusion",
    description: "Experiencia sensorial futurista para bares y conceptos modernos.",
    primaryColor: "#B16BE0",
    secondaryColor: "#0D0A14",
    backgroundColor: "#0D0A14",
    accentColor: "#29D6E8",
    textColor: "#F0F6FC",
    cardBackground: "#1A1626",
    fontTitle: "Staatliches",
    fontBody: "Inter",
    fontAccent: "Staatliches",
  },
  {
    id: "mediterranean",
    name: "Oliva & Mediterráneo",
    description: "Tradición y frescura saludable inspirada en las costas europeas.",
    primaryColor: "#6A8A3D",
    secondaryColor: "#152929",
    backgroundColor: "#FEFAE0",
    accentColor: "#F25129",
    textColor: "#152929",
    cardBackground: "#FFFFFF",
    fontTitle: "Playfair Display",
    fontBody: "Outfit",
    fontAccent: "Playfair Display",
  },
  {
    id: "gourmet",
    name: "Boutique Gastronomique",
    description: "Lujo, elegancia y sofisticación para alta cocina.",
    primaryColor: "#C9A063",
    secondaryColor: "#1F2937",
    backgroundColor: "#0D1117",
    accentColor: "#FFFFFF",
    textColor: "#F0F6FC",
    cardBackground: "#161B22",
    fontTitle: "Playfair Display",
    fontBody: "Lora",
    fontAccent: "Playfair Display",
  },
  {
    id: "organic",
    name: "Orgánico & Vital",
    description: "Conexión natural y bienestar en cada ingrediente.",
    primaryColor: "#6B8F71",
    secondaryColor: "#B9C4B1",
    backgroundColor: "#F8F9F5",
    accentColor: "#2C3E2D",
    textColor: "#2C3E2D",
    cardBackground: "#FFFFFF",
    fontTitle: "Quicksand",
    fontBody: "Open Sans",
    fontAccent: "Quicksand",
  },
  {
    id: "fusion",
    name: "Fusión de Autor",
    description: "Vanguardia, energía y creatividad sin límites.",
    primaryColor: "#FF3E00",
    secondaryColor: "#1A1A1A",
    backgroundColor: "#050505",
    accentColor: "#00F2FF",
    textColor: "#FFFFFF",
    cardBackground: "#0F0F0F",
    fontTitle: "Montserrat",
    fontBody: "Inter",
    fontAccent: "Montserrat",
  },
  {
    id: "seafood",
    name: "Brisa Marina",
    description: "Estilo mediterráneo enfocado en pescados y mariscos.",
    primaryColor: "#0077B6",
    secondaryColor: "#90E0EF",
    backgroundColor: "#F0F7FF",
    accentColor: "#CAF0F8",
    textColor: "#03045E",
    cardBackground: "#FFFFFF",
    fontTitle: "Raleway",
    fontBody: "Lato",
    fontAccent: "Raleway",
  },
  {
    id: "steakhouse",
    name: "Brasa & Linaje",
    description: "Tradición, fuego y carácter para parrillas de autor.",
    primaryColor: "#8B2635",
    secondaryColor: "#3E2723",
    backgroundColor: "#1A0F0A",
    accentColor: "#D4A373",
    textColor: "#FAEDCD",
    cardBackground: "#2B1D19",
    fontTitle: "Archivo Black",
    fontBody: "Roboto",
    fontAccent: "Archivo Black",
  },
  {
    id: "zen",
    name: "Kyoto Minimalist",
    description: "Minimalismo, calma y balance para cocina oriental.",
    primaryColor: "#111111",
    secondaryColor: "#E5E5E5",
    backgroundColor: "#FFFFFF",
    accentColor: "#999999",
    textColor: "#111111",
    cardBackground: "#F5F5F5",
    fontTitle: "Syne",
    fontBody: "Outfit",
    fontAccent: "Syne",
  },
  {
    id: "pastry",
    name: "Petit Plaisir",
    description: "Suavidad, color y dulzura para pastelerías de autor.",
    primaryColor: "#F7AEF8",
    secondaryColor: "#B3DEE2",
    backgroundColor: "#FFFAFB",
    accentColor: "#FBE7C6",
    textColor: "#4A4A4A",
    cardBackground: "#FFFFFF",
    fontTitle: "Quicksand",
    fontBody: "Nunito",
    fontAccent: "Quicksand",
  },
  {
    id: "brewery",
    name: "Distrito Industrial",
    description: "Estilo robusto y urbano para cervecerías y gastropubs.",
    primaryColor: "#D97706",
    secondaryColor: "#404040",
    backgroundColor: "#121212",
    accentColor: "#FBBF24",
    textColor: "#E5E5E5",
    cardBackground: "#1A1A1A",
    fontTitle: "Bebas Neue",
    fontBody: "Barlow",
    fontAccent: "Bebas Neue",
  },
  {
    id: "burger",
    name: "Garage Burger",
    description: "Identidad dinámica y directa para comida rápida gourmet.",
    primaryColor: "#E11D48",
    secondaryColor: "#FBBF24",
    backgroundColor: "#FFFFFF",
    accentColor: "#111827",
    textColor: "#111827",
    cardBackground: "#F9FAFB",
    fontTitle: "Montserrat",
    fontBody: "Inter",
    fontAccent: "Montserrat",
  },
  {
    id: "tropical",
    name: "Bahía Tropical",
    description: "Exotismo vibrante para bares y coctelería de verano.",
    primaryColor: "#10B981",
    secondaryColor: "#F97316",
    backgroundColor: "#064E3B",
    accentColor: "#EC4899",
    textColor: "#ECFDF5",
    cardBackground: "#064E3B",
    fontTitle: "Poppins",
    fontBody: "Outfit",
    fontAccent: "Poppins",
  },
  {
    id: "trattoria",
    name: "Raíces de Italia",
    description: "Ambiente acogedor y sabor tradicional de la cocina italiana.",
    primaryColor: "#BC6C25",
    secondaryColor: "#606C38",
    backgroundColor: "#FEFAE0",
    accentColor: "#DDA15E",
    textColor: "#283618",
    cardBackground: "#FFFFFF",
    fontTitle: "Lora",
    fontBody: "Montserrat",
    fontAccent: "Lora",
  },
  {
    id: "coffee",
    name: "Aroma & Grano",
    description: "Profundidad y calidez para cafeterías y tostadurías.",
    primaryColor: "#D4A373",
    secondaryColor: "#A98467",
    backgroundColor: "#2C1B10",
    accentColor: "#FEFAE0",
    textColor: "#FAEDCD",
    cardBackground: "#3B2B1D",
    fontTitle: "Outfit",
    fontBody: "Roboto",
    fontAccent: "Outfit",
  },
  {
    id: "wine_reserve",
    name: "Cava & Reserva",
    description: "Sofisticación y profundidad para experiencias de maridaje.",
    primaryColor: "#581845",
    secondaryColor: "#1F2937",
    backgroundColor: "#1A0A0F",
    accentColor: "#FFC300",
    textColor: "#FDF5E6",
    cardBackground: "#2B1D19",
    fontTitle: "Bodoni Moda",
    fontBody: "EB Garamond",
    fontAccent: "Bodoni Moda",
  },
];
