name: Notion Documentation Sync

on:
  push:
    branches: [ feature/docs, main ]
    paths:
      - 'Documentacion/**'

jobs:
  notion-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Sync Markdown to Notion
        uses: dvanoni/notion-documentation-sync@v1
        with:
          notion_token: ${{ secrets.NOTION_TOKEN }}
          notion_database_id: ${{ secrets.NOTION_DATABASE_ID }}
          docs_directory: 'Documentacion/01_Documentacion'
          # Filtra para evitar subir archivos no deseados
          filter: '.*\.md$'
